security:
    # Configuration des hachages de mot de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Configuration des fournisseurs de données (providers)
    providers:
        employe_provider:
            entity:
                class: App\Entity\Employe
                property: matricule

        client_provider:
            entity:
                class: App\Entity\Client
                property: email

    # Configuration globale de la sécurité
    # ...

    # Configuration des pare-feux (firewalls)
    # firewalls:
    #     dev:
    #         pattern: ^/(_(profiler|wdt)|css|images|js)/
    #         security: false

        main:
            custom_authenticator: 
                - App\Security\ClientAuthenticator
                - App\Security\EmployeAuthenticator
            entry_point: App\Security\ClientAuthenticator
            logout:
                path: app_logout

        client_login:
            pattern: ^/login_client
            provider: client_provider
            custom_authenticator: App\Security\ClientAuthenticator
            form_login:
                username_parameter: email
                password_parameter: password
                login_path: app_login_client
                check_path: app_login_client
                enable_csrf: true
            logout:
                path: app_logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path: /
            entry_point: App\Security\ClientAuthenticator

        employe_login:
            pattern: ^/login_employe
            provider: employe_provider
            custom_authenticator: App\Security\EmployeAuthenticator
            form_login:
                username_parameter: matricule
                password_parameter: password
                login_path: app_login_employe
                check_path: app_login_employe
                enable_csrf: true
            logout:
                path: app_logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path: /
            entry_point: App\Security\EmployeAuthenticator

    access_control:
        # - { path: ^/login_client, roles: IS_AUTHENTICATED_ANONYMOUSLY }


            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Configuration de l'accès aux ressources
    access_control:
        - { path: ^/gestion, roles: ROLE_EXPERT }
        - { path: ^/(demande|traitement), roles: ROLE_SENIOR }
        - { path: ^/(demande|traitement), roles: ROLE_APPRENTI }
    role_hierarchy:
        ROLE_APPRENTI: ROLE_SENIOR
        ROLE_EXPERT: ROLE_SENIOR
       

when@test:
    # Configuration spécifique pour les tests
    security:
        password_hashers:
            # Configuration des hachages de mot de passe pour les tests
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
