security:
    # Configuration des hachages de mot de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Configuration des fournisseurs de données (providers)
    providers:
        employe_provider:
            entity:
                class: App\Entity\Employe
                property: matricule

        client_provider:
            entity:
                class: App\Entity\Client
                property: email

    # Configuration globale de la sécurité
    # ...

    # Configuration des pare-feux (firewalls)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # main:
        #     lazy: true
        #     provider: app_user_provider
        #     custom_authenticator: App\Security\EmployeAuthenticator
        #     logout:
        #         path: app_logout
                # where to redirect after logout
                # target: app_any_route

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Configuration de l'accès aux ressources
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    # Configuration spécifique pour les tests
    security:
        password_hashers:
            # Configuration des hachages de mot de passe pour les tests
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
